version: '3'
services:
  app:
    container_name: full_app
    build: .
    ports: 
      - 3001:3001 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - fullstack-postgres          
    networks:
      - fullstack


  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_HOST=${DB_HOST} 
    ports:
      - '5433:5433'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    hostname: postgres-container

    

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge
