apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: blog1111
  POSTGRES_DB: blog
  DB_HOST: fullstack-postgres
  DB_DRIVER: postgres
  API_SECRET: 98hbun98h
  DB_USER: postgres
  DB_PASSWORD: blog1111
  DB_NAME: blog
  DB_PORT: "5432"